### ISSUE TITLE
preg_match(): Argument #2 ($subject) must be of type string, LemonSqueezy\Laravel\Checkout given

### ISSUE THREAD

**Issue by ap1969** [lmsqueezy/laravel#10]
Hi,
I've got the sample subscription route set up as follows:

```
Route::get('/subscribe', function (Request $request) {
    return redirect(
        $request->user()->subscribe('53900')
    );
});
```

But I get the above preg_match error from  the line with the subscribe() function.

Regards,
Andy

**Comment by driesvints** [comment]
hmm that's odd. Any chance you have the complete stacktrace?

**Comment by driesvints** [comment]
Btw, just FYI. You don't need `redirect()`:

```php
Route::get('/subscribe', function (Request $request) {
    return $request->user()->subscribe('53900');
});
```

**Comment by driesvints** [comment]
Hah, I now realise I can make all of the examples in the docs easier 😂

**Comment by ap1969** [comment]
Sorry - thought I replied here earlier, to say that's fixed.

Thanks Dries.
