### ISSUE TITLE
Laravel 11 + PHP 8.3 - can't install

### ISSUE THREAD

**Issue by BKirev** [lmsqueezy/laravel#106]
### Lemon Squeezy for Laravel Version

1.6.2

### Laravel Version

11.25.0

### PHP Version

8.3.12

### Description

```- lemonsqueezy/laravel 1.6.2 requires laravel/prompts ^0.1 -> found laravel/prompts[v0.1.0, ..., v0.1.25] but the package is fixed to v0.2.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.```

### Steps To Reproduce

```composer require lemonsqueezy/laravel:1.6.2```

on a server with the provided details.

**Comment by driesvints** [comment]
Fixed.
