### ISSUE TITLE
Subscription model does not have a `hasExpiredTrial` method

### ISSUE THREAD

**Issue by jbrooksuk** [lmsqueezy/laravel#11]
`ManagesSubscriptions` has a method `hasExpiredTrial` which runs:

```php
if (! $subscription || ! $subscription->hasExpiredTrial()) {
    return false;
}
```

However, the `Subscription` model does not include a `hasExpiredTrial` method.

**Comment by driesvints** [comment]
Thanks! Will try to add this soon or merge a PR if anyone's up for it.

**Comment by driesvints** [comment]
Fixed
