### ISSUE TITLE
Redirect to customer portal is throwing a type error

### ISSUE THREAD

**Issue by AKurka** [lmsqueezy/laravel#112]
### Lemon Squeezy for Laravel Version

1.7.0

### Laravel Version

11.9

### PHP Version

8.3.13

### Description

Hi !

I installed the lemonsqueezy laravel package to use it in an app with Inertia. I'm getting errors while trying to access the the customer portal.

I get this Laravel error :

```
App\Models\User::customerPortalUrl(): Return value must be of type string, null returned
```

### Global

I added the billable trait to my User model.

I added this cast because i'm using an enum for my country value :
```php
public function lemonSqueezyCountry(): ?string
    {
        return strtoupper($this->country->value);
    }
```

### For the customer portal

I call a route using this method : 
```php
public function __invoke(Request $request)
    {
        return $request->user()->redirectToCustomerPortal();
    }
```

**Comment by AKurka** [comment]
### EDIT :

I investigated in the sources files and the error come from this function : `customerPortalUrl` in the `ManageCustomer`trait.

The customer_portal URL is null. The response come from this request : 
```php
$response = LemonSqueezy::api('GET', "customers/{$this->customer->lemon_squeezy_id}");
```

**Comment by AKurka** [comment]
Yes ! I’ve alerady made a payment with lemonsqueezy. I checker the order id, the customer id and everything is filled.

**Comment by driesvints** [comment]
Actually it seems the requirement is to have a subscription. See https://docs.lemonsqueezy.com/api/customers/the-customer-object#urls

I've updated the docs.
