### ISSUE TITLE
Command to list product and variants

### ISSUE THREAD

**Issue by jbrooksuk** [lmsqueezy/laravel#12]
Since Lemon Squeezy's dashboard does not have a nice way to see the product / variant IDs, it could be useful if this package included an Artisan command to list products and their variants, so you can find them quickly.

**Comment by driesvints** [comment]
Cool, yeah this is planned on the roadmap 👍

**Comment by farez** [comment]
Struggling with this actually. How do I find the default variant's ID?

**Comment by driesvints** [comment]
@farez I suggest creating an actual variant if you can't find it in the UI.

**Comment by abishekrsrikaanth** [comment]
You can actually do this on the lmsqueezy products page 
![CleanShot 2023-08-05 at 23 13 48](https://github.com/lmsqueezy/laravel/assets/1639302/4bbc2946-e908-4fa1-b42a-4fd85aea37bf)

**Comment by jbrooksuk** [comment]
> You can actually do this on the lmsqueezy products page 
> 
> ![CleanShot 2023-08-05 at 23 13 48](https://github.com/lmsqueezy/laravel/assets/1639302/4bbc2946-e908-4fa1-b42a-4fd85aea37bf)
> 
> 

I think that's new!

**Comment by heyjorgedev** [comment]
@driesvints is this still relevant? if not, would be nice to close old issues so that I can see where I could help

**Comment by driesvints** [comment]
Hey @heyjorgedev yeah it is. I just didn't get around this yet.

**Comment by driesvints** [comment]
I appreciate the help btw!

**Comment by heyjorgedev** [comment]
@driesvints  @jbrooksuk What do you think we should include as details?

Name, Product/Variant ID, but should we also include that the product/variant is in test mode and the price? or is it too much clutter? What did you had in mind?

![Screenshot 2024-03-20 at 11 02 52](https://github.com/lmsqueezy/laravel/assets/2780099/66812ad2-c9a1-4e68-9c9a-03896c56cace)

**Comment by driesvints** [comment]
@heyjorgedev looks very cool! I'd rename the command to `lmsqueezy:products` and the command class to `ListProductsCommand`. 

I wouldn't indicate test mode of now. I like that the price is next to the price name. Looks good! Can you also do a lookup by product ID? e.g. `php artisan lmsqueezy:products 3123123`?

**Comment by heyjorgedev** [comment]
@driesvints is there anything that I need to do to be able to run the Feature tests? Cloning the project fresh and running the tests with pest yields to Unit tests passing but Feature tests failing. Debugged it a bit and found that removing the RefreshDatabase trait "helps" but of course that's not a solution. Do you have any advice? Otherwise I can keep debugging

**Comment by heyjorgedev** [comment]
Gotcha, it's also failing on the CI

Laravel 10 - PHP 8.3 - Passing: https://github.com/lmsqueezy/laravel/actions/runs/8352088440/job/22861603583
Laravel 11 - PHP 8.3 - Failing (even tho the CI is green): https://github.com/lmsqueezy/laravel/actions/runs/8352088440/job/22861603732

**Comment by driesvints** [comment]
@heyjorgedev dang that's not good. Will investigate that.

**Comment by heyjorgedev** [comment]
@driesvints I have the implementation done, working on the tests but do you think it makes sense to open a draft PR so we can discuss the implementation?

**Comment by driesvints** [comment]
@heyjorgedev sure thing. Thanks!

@nunomaduro actually found out it's related to the `exit()` calls in the command. We should convert those to integer returns and return the failure status from the main command handle.

**Comment by heyjorgedev** [comment]
Ahh, its the artisan calls on the ListenCommandTest... just removed them and got the tests to error well. nice one... If you don't have time I would also be open to do another PR to solve the tests on Laravel 11 and to refactor this

**Comment by driesvints** [comment]
Would definitely appreciate it!

**Comment by driesvints** [comment]
This one is now released in v1.6.0
