### ISSUE TITLE
Return from `updatePaymentMethodUrl`

### ISSUE THREAD

**Issue by jbrooksuk** [lmsqueezy/laravel#14]
This may be an issue with Lemon Squeezy itself (I've not looked into the API used) but when you follow the URL to update payment methods, the page shows a (X) button that doesn't do anything.

<img width="780" alt="CleanShot 2023-05-05 at 08 59 51@2x" src="https://user-images.githubusercontent.com/246103/236405736-d57a1a52-aab7-4ca3-aac6-f6eb7ca9eb6f.png">

Is it possible to modify this link in some way?

**Comment by driesvints** [comment]
Hmm, I'll forward this to LS, thanks.

**Comment by driesvints** [comment]
Seems like it's mostly intended for this to work with the embedded overlay. I'll update the docs soon to reflect this.

**Comment by jbrooksuk** [comment]
@driesvints is there a preferred way to handle this for custom applications that aren't using the embedded overlay?

**Comment by driesvints** [comment]
@jbrooksuk the example from the docs right now. But it's not optimized for it (like the issue you're facing). They're fixing this soon.

**Comment by driesvints** [comment]
I can't seem to get the overlay to work with the payment method details url right now. Pinged LS and will follow up with them.

**Comment by driesvints** [comment]
Updated the docs to include an example with Lemon.js
