### ISSUE TITLE
customers table - lemon_squeezy_id is not nullable for trial without card

### ISSUE THREAD

**Issue by sohaibilyas** [lmsqueezy/laravel#15]
I was trying to create 2 user account on trial without card using this method createAsCustomer() but got this error:

`1062 Duplicate entry '' for key 'lemon_squeezy_customers.lemon_squeezy_customers_lemon_squeezy_id_unique`

https://github.com/lmsqueezy/laravel/blob/main/database/migrations/2023_01_16_000001_create_customers_table.php#L15 here lemon_squeezy_id is unique and not nullable so it means we cant create 2 users on trial without card, or is it fine to just add random id!

**Comment by driesvints** [comment]
Thank you. I fixed this but a migration got changed so you might need to re-run those.
