### ISSUE TITLE
Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by romaldyminaya** [lmsqueezy/laravel#17]
Hi team,

I'm trying to generate the subscription link but I get this error message, over and over again.
![image](https://github.com/lmsqueezy/laravel/assets/2809147/ac5adc18-ef11-4302-b7ab-d4215fbe0c84)

Here I cannot generate the link and I followed all the steps from the documentation:

![image](https://github.com/lmsqueezy/laravel/assets/2809147/35f97f73-9ec9-4167-af43-263d574b44e5)

**Comment by romaldyminaya** [comment]
I did a DD in inside the subscribe -> checkout method and the guzzle is returning a 404.
![image](https://github.com/lmsqueezy/laravel/assets/2809147/54d93305-0060-4e98-aa2b-c119cc9ae3a6)

**Comment by driesvints** [comment]
@romaldyminaya LS let me know that they pushed a fix for this. Can you try again?

**Comment by driesvints** [comment]
> I must tell that I'm using the billable trait not in a user model but a company model instead.

hmm that shouldn't matter really. Are you sure you're using the correct api key for the correct environment? Is this production or testing?

**Comment by driesvints** [comment]
The variant ID you're sharing exists in your Lemon Squeezy dashboard in a product? Can you post a screenshot of that as proof?

**Comment by romaldyminaya** [comment]
Hi @driesvints ,

Would it be that I'm using the wrong code, would you mind please share with me a screenshot of what code are you using too ?

![image](https://github.com/lmsqueezy/laravel/assets/2809147/c7f4d851-db3a-4a6a-9348-1cd59e8199a6)

**Comment by driesvints** [comment]
Your variant id from your code example doesn’t seem to match with the length of your variant id. Are you sure you’re using a variant id? It seems to have the length of a uuid but you’ve covered it up so I’m not sure.

**Comment by romaldyminaya** [comment]
Hi @driesvints ,

This is the resonse I get from the GET VARIANTS endpoint:

![image](https://github.com/lmsqueezy/laravel/assets/2809147/53ff680e-8e2f-4aee-876e-715290010b94)

Im using the code pointed with the yellow draw line. But still have the same results.

In the lemon squeeze panel I don't see a place where we can copy or paste the id for a specific subscription created.

![image](https://github.com/lmsqueezy/laravel/assets/2809147/7c79533f-9eed-4b76-b1a9-50184dd535ea)

I tried passing the product name, product slug, product id, product's variant id, product's variant slug and still have the same response.

**Comment by driesvints** [comment]
You don’t need the slug. You need the id from one level up. It’s the variant id you need.

**Comment by romaldyminaya** [comment]
Hi @driesvints ,

Now I found the problem. When I updated, i didn't refresh the config so I had the wrong store ID requested by the same config file:

```
    /*
    |--------------------------------------------------------------------------
    | Lemon Squeezy Store
    |--------------------------------------------------------------------------
    |
    | This is the ID of your Lemon Squeezy store. You can find your store
    | ID in the Lemon Squeezy dashboard. The entered value should be the
    | part after the # sign.
    |
    */

    'store' => env('LEMON_SQUEEZY_STORE'),
```

Now its working, thanks in advance.

**Comment by driesvints** [comment]
@romaldyminaya ah great
