### ISSUE TITLE
Subscriptions created as orders

### ISSUE THREAD

**Issue by jbrooksuk** [lmsqueezy/laravel#18]
I have six subscriptions configured in my store. I used the "Copy to Live Mode" dropdown option to copy my test mode subscription into live (I mention this, as I wonder if this is why it's broken).

Each subscription has two variants, each set as "Subscription", with a 14 day free trial:

1. Monthly
2. Yearly

No product has any downloadable content attached, and yet, when I create a new subscription from my app:

```php
public function checkout(Request $request)
{
    return current_team()
        ->subscribe($request->input('variantId'))
        ->withName(current_team()->owner->name)
        ->withEmail(current_team()->owner->email)
        ->redirectTo(route('billing.index'));
}
```

The Lemon Squeezy check out page says "Start Trial" and when I click that, I'm told that I'll receive instructions via email. The email also says "Download Content", but again **there is no content to download**.

Further, webhooks are firing as `order_created` rather than anything about subscriptions.

**Comment by driesvints** [comment]
Thanks @jbrooksuk. Is there a log or something from the lemon squeezy dashboard for the checkout creation? Might give us some more info here.

**Comment by jbrooksuk** [comment]
@driesvints I can't find any logs within the Lemon Squeezy dashboard, sorry.

Oh, also adding that I'm using v0.2.0.

**Comment by gilbitron** [comment]
> The email also says "Download Content", but again there is no content to download.

@jbrooksuk This can be changed in your product settings under **Receipt**.

> Further, webhooks are firing as order_created rather than anything about subscriptions.

You should be receiving `subscription_created` webhooks. You can get in touch with our support team at hello@lemonsqueezy.com for more help with Lemon Squeezy related issues.

**Comment by driesvints** [comment]
I'll close this then but definitely report back once you find what's wrong 👍

**Comment by ArondeParon** [comment]
@jbrooksuk have you managed to resolve this issue? I am experiencing the exact same issue when going to production just now.

**Comment by ArondeParon** [comment]
> @ArondeParon are you using a 100% discount code by any chance?

Yes! Just discovered the same. Seems this breaks the subscription vs. order, but also the text on checkout screen (will default do "Download..." when using a discount code). Assuming this was your issue as well, so will relay this to Lemonsqueezy.

Sorry for the slightly offtopic conversation here Dries 😅 I can imagine that a lot of users are going to run into this until this is fixed by the Lemonsqueezy team, so perhaps this will help someone in the near future.

**Comment by jbrooksuk** [comment]
@ArondeParon yeah, Lemon Squeezy doesn't support "free subscriptions". I've discussed this with [Dan](https://twitter.com/dr) and it's something they're going to look at, but for now there are some inconsistencies.
