### ISSUE TITLE
Webhook received but no handler found

### ISSUE THREAD

**Issue by wassim** [lmsqueezy/laravel#24]
The database doesn't get updated after a successful payment. Tested locally and on prod.

`Webhook received but no handler found.`

I've followed the docs and added `'lemon-squeezy/*'` to `App\Http\Middleware\VerifyCsrfToken` except list

**More info**
Tested with a single payment variant

```php
public function checkout(Request $request)
{
    return $request->user()
        →checkout(config('lemon-squeezy.lifetme_deal_variant_id'))
        →redirectTo(url(RouteServiceProvider::HOME));
}
```

The payment succeed and I'm redirected to the redirect URL, but the database doesn't get updated (customers and subscriptions)

On LM webhooks screen I see this:

![CleanShot 2023-05-22 at 15 19 12@2x](https://github.com/lmsqueezy/laravel/assets/14947638/fb77ebbb-b07c-4b24-afd3-bc3e9ca34955)

Expected behavior:
- Database gets updated accordingly

**Comment by driesvints** [comment]
Can you please share more info here? What is this about? A single payment? A subscription? What code did you use, what happened and what did you expect to happen?

**Comment by wassim** [comment]
@driesvints updated

**Comment by driesvints** [comment]
Hi there. Nothing is supposed to get updated here. Nothing gets handled for single payments, only for subscriptions. It says no handler was found because there is no handler (yet) for successful payments.

**Comment by wassim** [comment]
Thanks. I've created a custom handler.
