### ISSUE TITLE
Single charge with no product

### ISSUE THREAD

**Issue by nam-co** [lmsqueezy/laravel#25]
Hi, is there a way to create a simple checkout with just the price? (no product or subscription, no model) just say I send to the API: price is $10usd, collect tax, product name, etc.. and it returns if success or not

Appreciate any help
Thank you

**Comment by mraheelkhan** [comment]
#28  i have added a PR for custom price.

**Comment by driesvints** [comment]
@nam-co unfortunately Lemon Squeezy doesn't seems to support that. The best thing you can do is create a "generic" product that you can use to dynamically charge against. I've just merged @mraheelkhan's PR so that should be available shortly.
