### ISSUE TITLE
redirectTo parameter not doing anything?

### ISSUE THREAD

**Issue by ArondeParon** [lmsqueezy/laravel#27]
I assume that I am most likely doing something wrong, but I have checked my implementation with the documentation and can't seem to find anything wrong with it.

I have tried redirecting to a checkout URL:

```php
        $checkout = $request->user()->checkout($chosenVariant)
            ->redirectTo(route('subscription.complete'));
```

... and have tried doing the same using the `subscribe` method:

```php
        $checkout = $request->user()->subscribe($chosenVariant)
            ->redirectTo(route('subscription.complete'));
```

But either way, after making a succesful (test) payment, I am still stuck in the LemonSqueezy page instead of being redirected back.

Am I missing something?

**Comment by driesvints** [comment]
That's odd. That should definitely work. I'll have to try this myself in order to confirm.

**Comment by ArondeParon** [comment]
Thanks, let me know if I can help! :)

**Comment by ArondeParon** [comment]
FYI I have this setting turned off in the dashboard because I figured that it might conflict with the dynamic URL.
![CleanShot 2023-05-31 at 16 49 28](https://github.com/lmsqueezy/laravel/assets/7697/2b5a3bb3-bad7-4dc6-8c64-84a2ae0ae1d7)

**Comment by mraheelkhan** [comment]
@ArondeParon, I tried to replicate this issue but it seems working for me and both methods redirect back to the dashboard after checkout. 

Tried with checkout
```
$request->user()
        ->checkout('1234')
        ->redirectTo(route('dashboard'));
```
Tried with subscribe
```
$request->user()
        ->subscribe('12345')
        ->redirectTo(route('dashboard'));
```

cc @driesvints

**Comment by ArondeParon** [comment]
Hmm that is super weird. Did you try on the test or production environment? I tried this on test (no prod setup yet) and don't see the redirect happening.

**Comment by mraheelkhan** [comment]
I tried dev/test mode. 
I have Laravel `10.13.1` and LemonSqueezy `0.2.1`.

**Comment by ArondeParon** [comment]
Issue resolved! 🥳 

The issue was caused by (who would have thought!) stupid code on my end 😅 

My "checkout complete" page was causing an infinite redirect. LMS is smart enough to check for this before actually redirecting, which caused the behaviour I was seeing.
