### ISSUE TITLE
The product options.redirect url must be a valid URL.

### ISSUE THREAD

**Issue by Christopher-Law** [lmsqueezy/laravel#31]
When attempting to subscribe to a product using its variant_id I see the error: The product options.redirect url must be a valid URL.

I have set up a store, set my env vars, created a subscription product and added a valid redirect url ( it saves correctly on lemon squeezy ).

**Comment by driesvints** [comment]
Hi there. I'll need much more into to debug this:

- Code example of what you're trying to do and to reproduce it
- Screenshot of the product and its variant with its settings

Then I can try and reproduce this

**Comment by koossaayy** [comment]
Hello @Christopher-Law , I just ran into the problem, but I have solved it as follows, 
I have published the config file, updated the `redirect_url` key with a valid URL like `https://yoursite.com/thankyou`
Also, I have put the same value in LemonSqueezy dashboard as follows 
![image](https://github.com/lmsqueezy/laravel/assets/6431084/aa7616d6-09f3-4ef8-b99f-723e4ff612ce)

And it worked

**Comment by driesvints** [comment]
@Christopher-Law did @koossaayy' answer help you?

**Comment by driesvints** [comment]
@Christopher-Law feel free to resubmit this one if you're still experiencing it. Thanks
