### ISSUE TITLE
Invalid signature.

### ISSUE THREAD

**Issue by luissandrea** [lmsqueezy/laravel#4]
<img width="461" alt="Captura de pantalla 2023-04-24 a la(s) 10 53 40 p  m" src="https://user-images.githubusercontent.com/16054416/234170658-f3851e07-3cfa-4974-aeab-f777740c2bcf.png">

Code:

```
Route::get('buy', function (Request $request) {
    $checkout = $request->user()->checkout('variant_id')->redirectTo(url('/'));

    return view('billing', ['checkout' => $checkout]);
});
```

In a local environment

**Comment by driesvints** [comment]
Did you replace `'variant_id'` with an actual variant ID from your store? What are the contents of `billing`? Is this a plain Laravel app or are you using Breeze, etc?

**Comment by srloois** [comment]
1. Yes, I did

2. billing:

```
@extends('layouts.master')

@props(['navigation' => false])

@section('content')
    <x-lemon-button :href="$checkout" class="px-8 py-4">
        Buy Product
    </x-lemon-button>
@endsection
```

3: It's a Laravel app

**Comment by srloois** [comment]
UPDATE: 

If I redirect instead of showing the button, it works.

e.g.

```
Route::get('buy', function (Request $request) {
    $checkout = $request->user()->checkout('variant_id');

    return redirect($checkout->url());
});
```

**Comment by driesvints** [comment]
I can confirm that this doesn't works right now. Waiting on the LS team for feedback.

Redirects should also just work like this btw:

```php
Route::get('buy', function (Request $request) {
    return $request->user()->checkout('variant_id');
});
```

**Comment by claudiodekker** [comment]
@driesvints Should be fixed now. Could you verify this?
