### ISSUE TITLE
Sync Subscription billing_anchor to db

### ISSUE THREAD

**Issue by prismosoft** [lmsqueezy/laravel#43]
Thank you for this great package!

I think the Subscription billing_anchor field needs to be synced to the db as well, this would be useful in case our monthly plans have monthly limits. Example X messages per month. In that case, we need to know the Billing cycle to calculate usage within the cycle.

For now, I am modifying the migration, listening to the create / update events, and re-update the subscription model a second time.

**Comment by driesvints** [comment]
Is this related to Lemon Squeezy's new metered billing? I still need time to check into all of that...

**Comment by prismosoft** [comment]
Sorry about that, this is not needed, there is already a **renews_at** field for that purpose, I completely missed it!
