### ISSUE TITLE
Field 'lemon_squeezy_id' doesn't have a default value

### ISSUE THREAD

**Issue by rvetrsek** [lmsqueezy/laravel#49]
### Lemon Squeezy for Laravel Version

1.2.2

### Laravel Version

10.26.2

### PHP Version

8.2

### Description

The recent change to the [2023_01_16_000001_create_customers_table.php](https://github.com/lmsqueezy/laravel/commit/689faccde4a4e4fffb84f09d49ad1e724b160134#diff-dddbedbe1fd5f90ebe6e00e0d94bdad46e82bf99979e033da37d8cb517558f62) migration reopened a issue that was closed some time ago ([https://github.com/lmsqueezy/laravel/issues/15](https://github.com/lmsqueezy/laravel/issues/15)).

Can this be fixed/reverted, or is it required just to generate a unique `lemon_squeezy_id` if creating a No Payment Required trial?

### Steps To Reproduce

Create a No Payment Required trial for a user by following the readme:

```PHP
use App\Models\User;
 
$user = User::create([
    // ...
]);
 
$user->createAsCustomer([
    'trial_ends_at' => now()->addDays(10)
]);
```

**Comment by driesvints** [comment]
Dang, sorry. Released v1.2.3 that fixes this.
