### ISSUE TITLE
The related resource does not exist.

### ISSUE THREAD

**Issue by iamnitinviras** [lmsqueezy/laravel#70]
### Lemon Squeezy for Laravel Version

1.4

### Laravel Version

10.0

### PHP Version

8.2.0

### Description

I am trying the below code to subscribe or checkout but it gives me an error.

```
Route::get('/subscribe', function (Request $request) {
            return $request->user()->subscribe('151662');
            //return $request->user()->checkout('148944');
        });
```

![error](https://github.com/lmsqueezy/laravel/assets/15800722/93fb537b-d97d-4362-9156-5d25700e212d)

### Steps To Reproduce

When adding subscribe code in the route it gives "The related resource does not exist." error

**Comment by tao** [comment]
For anyone else that might encounter this issue in the future, the products variant ID changes if you modify or update the product information in the LemonSqueezy dashboard.
