### ISSUE TITLE
"The related resource does not exist." Error on Production 

### ISSUE THREAD

**Issue by ianclemence** [lmsqueezy/laravel#74]
I've just integrated Lemon Squeezy into my Laravel app, following the documentation meticulously. Webhooks are working smoothly in Test mode, but when I switch to live mode, I encounter the error "The related resource does not exist." I've double-checked my setup against the documentation. Has anyone else faced this problem?

**Comment by driesvints** [comment]
You're certain the ID is of variant of a TEST product? And your API keys are testing API keys?

**Comment by ianclemence** [comment]
I realized I didn't update my variant-id in env file. 

Closing this issue now
