### ISSUE TITLE
Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by ousid** [lmsqueezy/laravel#9]
Trying to run a checkout with a variant ID, but I got the following issue: `Trying to access array offset on value of type null`

## Steps to produce
- Create a product
- Create variants
- Get the Variant ID
- Create a checkout from an existing user
- pass the checkout variable to `x-lemon-button`
- Trying to access the pricing page.

## Code sample:

```php
public function __invoke()
{
   /** @var \App\Models\User */
   $user = Auth::user();
   $checkout = $user?->checkout('variant-id');

   return view('pricing', ....);
}
```

## The Problem
After digging into the package source code, I found the issue in the `url()` method

## Suggested solution
For now, I didn't have any clue on where is the problem exactly is. I'll update the issue once I solved the problem, with a `PR`.

**Comment by driesvints** [comment]
Thanks @ousid. I'm afraid we'll need some more info here like details on how the product and variant were configured because right now this was tested and should work. Can you also share the full code on how you pass the checkout to the view as well as how you assign the checkout to the blade component?

**Comment by ousid** [comment]
Well, here are the steps on how it's done:

- Create New Product
- Add Variants inside the product (free-premium)
- Access the API endpoint to fetch the variants ID `https://api.lemonsqueezy.com/v1/products/{ID}/relationships/variants`
- Pass the variant `ID` into the controller

```php
    public function __invoke()
    {
        /** @var \App\Models\User */
        $user = Auth::user();
        $checkout = $user?->checkout('variant-id')
                        ?->withButtonColor('#F15BB5');

        return view('frontend.pricing', [
            'packages' => Package::get(),
            'checkout' => $checkout,
        ]);
    }
```

Here's the blade
```blade
<x-lemon-button 
    :href="$checkout" 
    class="cta-button" 
    aria-describedby="tier-standard">
    {{ $package->cta_button_text }}
</x-lemon-button>
```

when I `dd` the `$href` in the `button` component, it shows it's an instance from `LemonSqueezy\Laravel\Checkout`

You should note that the app is in __test mode__.

Here's a screenshot from the dashboard
![image](https://user-images.githubusercontent.com/21012933/236275313-455a4996-9e12-4f09-a726-bc4bdcdde13e.png)


__PS__: my app still in the dev mode, and I'm just testing the package out, to see if it works well.

**Comment by driesvints** [comment]
Hmm odd. It would help if you had an entire stacktrace to see where the error originates from.

**Comment by driesvints** [comment]
Feel free to re-open an issue once you have a complete stacktrace 👍
