### ISSUE TITLE
Undefined constant "LemonSqueezy\Laravel\Console\SIGINT"

### ISSUE THREAD

**Issue by smell-of-curry** [lmsqueezy/laravel#94]
### Lemon Squeezy for Laravel Version

1.5.4

### Laravel Version

10.48.7

### PHP Version

8.1

### Description

Im running `php artisan lmsqueezy:listen` and choosing `expose` and it says:
```
Error

  Undefined constant "LemonSqueezy\Laravel\Console\SIGINT"

  at vendor\lemonsqueezy\laravel\src\Console\ListenCommand.php:144
    140▕     protected function handleService(): int
    141▕     {
    142▕         note('Setting up webhooks domain with '.$this->argument('service').'...');
    143▕
  ➜ 144▕         $this->trap([SIGINT], fn (int $signal) => $this->teardownWebhook());
    145▕
    146▕         return $this->{$this->argument('service')}();
    147▕     }
    148▕

  1   vendor\lemonsqueezy\laravel\src\Console\ListenCommand.php:83
      LemonSqueezy\Laravel\Console\ListenCommand::handleService()

  2   vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:36
      LemonSqueezy\Laravel\Console\ListenCommand::handle()
      ```
![image](https://github.com/lmsqueezy/laravel/assets/75345244/d17802f2-b298-4cad-8b93-c8122d20f697)

### Steps To Reproduce

Fresh Install, run `php artisan lmsqueezy:listen`

**Comment by Afan417** [comment]
I am experiencing the same issue, in Windows 10 x64 bit, any help?

**Comment by heyjorgedev** [comment]
I believe PHP doesn't support signal handling on Windows. Therefore SIGINT is not an available constant.

@driesvints @DanielHudson maybe we could add a check to validate the command is being run on windows and provide this information as a console output and possible solutions?

**Comment by driesvints** [comment]
Thanks for reporting this one. Unfortunately the listen command cannot be used on windows due to the lack of signal handling on Windows. I've now added a warning to the command. Right now I don't have plans to develop support for Windows for this command but I'd very much accept PR's that could help out.

**Comment by Aecy** [comment]
Hello, so how to emulate for windows?
