### ISSUE TITLE
Undefined Array Key "errors" in LemonSqueezy API Method

### ISSUE THREAD

**Issue by prismosoft** [lmsqueezy/laravel#96]
### Lemon Squeezy for Laravel Version

1.5.4

### Laravel Version

10.48

### PHP Version

8.2

### Description

In the **`LemonSqueezy.php`** file, within the **`api` method**, **line 66**, the following line causes an `Undefined array key "errors"` error:

```php
throw new LemonSqueezyApiError($response['errors'][0]['detail'], (int) $response['errors'][0]['status']);
```

This occurs because $response is not an array but an Illuminate\Http\Client\Response object. Attempting to access it as an array causes an undefined key error.

**Proposed Fix:**

Replace the problematic line with:

```php
throw new LemonSqueezyApiError($response->json('message', ''), $response->status());
```

This uses the json method to extract the error message from the response body and the status method to get the HTTP status code.

### Steps To Reproduce

Call the LemonSqueezy::api method with parameters that would result in an error response from the API. Example:

```php
LemonSqueezy::api('get', 'invalid-endpoint')

**Comment by driesvints** [comment]
But this shouldn't happen because `Illuminate\Http\Client\Response` implements `ArrayAccess`. It's perfectly fine to use array syntax on it. If you run into `Undefined array key "errors"` then it means there's no such key even though the response failed. I wonder why.

Could you perhaps paste the entire response object you got back from Lemon Squeezy? Inspecting its contents could maybe show us where to look.

**Comment by driesvints** [comment]
Tried to reproduce but get a perfectly normal error:

<img width="1518" alt="Screenshot 2024-07-03 at 20 18 35" src="https://github.com/lmsqueezy/laravel/assets/594614/cfd688e6-777c-4928-925e-2301df23844d">

**Comment by juslintek** [comment]
I've got same problem as well it happens sporadically, when swap is performed.

**Comment by driesvints** [comment]
@juslintek there's three extra vendor frames after that line, maybe those help?

I'd need a clear way to reproduce this otherwise I'll be shooting in the dark.
