### ISSUE TITLE
Database empty after subscription

### ISSUE THREAD

**Issue by Aecy** [lmsqueezy/laravel#98]
### Lemon Squeezy for Laravel Version

^1.6

### Laravel Version

^11.9

### PHP Version

8.3.3

### Description

When i subscribed to a product (product with 2 variants, one for month and other for year subscription).

Wen I sub, all good. But my database is full empty.

### Steps To Reproduce

1. Subscribe to a plan
2. See the database empty

**Comment by driesvints** [comment]
Are you running the webhooks?

**Comment by Aecy** [comment]
Hey, yes. But Im working with Windows currently

**Comment by driesvints** [comment]
I don't understand. Why is that a problem? This should all work fine really. Could you please share a detailed step-by-step guide to reproduce the issue?

**Comment by driesvints** [comment]
Feel free to respond once you can.

**Comment by Aecy** [comment]
I deleted the repository. Maybe I will retry it after
